### ISSUE TITLE
bug: spoofing app versions 17.33.42 to 17.39.35 returns another type of update screen

### ISSUE THREAD

**Issue by jpa102** [kitadai31/revanced-patches-android6-7#99]
### Bug description

not really a bug *(don't know what to put or describe)*, but since i've seen the "Avoid Switch to youtube.com" in your readme.md, i thought to report this issue

so recently, youtube is now rolling out their update screens but in another way. like you can still navigate around the app, but it will show that update screen or return a http 400 error (happens on versions 17.33.42 all the way up to 18.49.37 stock app)

here are some screenshots from one of my builds:

![Image](https://github.com/user-attachments/assets/0b2e7a33-50b8-4278-9f6a-6abb386cbd1e)
![Image](https://github.com/user-attachments/assets/89723e7f-7409-49d2-b5c3-a8732a1ec6ce)

you can see it's different from this where all you can press is a button:

![Image](https://github.com/user-attachments/assets/3d945266-dedd-44d9-b8bb-b2c54ae3f09d)

***

if one decides to spoof the version to something like `19.02.39`, it functions almost like nothing happened until the shorts videos is played

![Image](https://github.com/user-attachments/assets/47dee9b5-1363-47fb-8fd0-7b8162390d33)
![Image](https://github.com/user-attachments/assets/4712a7f1-80ee-4b85-b035-187a0f25f053)
![Image](https://github.com/user-attachments/assets/d335ad63-0615-4f9b-8ed7-638c6f9eedf5)

occasionally, the library tab will turn into the "You" tab when spoofed to a certain 19.xx.xx version. but that is broken as well

### Error logs

```shell

```

### Solution

i don't think a solution can be made for this, as spoofing the base 17.34.36 to versions higher than 19.16.39 can cause severe bugs (i commented on the "andr5 dead again" issue from d4n3436's revanced-patches repository where the side effects in spoofing the 16.40
36 to the 19.xx.xx versions are much more severe

### Additional context

for the first screenshot shown, i'm using a old version of your revanced patches but this should apply to your latest patches as well

![Image](https://github.com/user-attachments/assets/acf5600f-2784-4515-b826-bba4bfbab432)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by steprtm** [comment]
can you tell me how to spoof version?

**Comment by kitadai31** [comment]
Yes. it is happening.
I added an explain about it to readme.
Please see it.
https://github.com/kitadai31/revanced-patches-android6-7/blob/ca2f33a2ad8065200e411b7670b9089922c32b9b/README.md#a-quick-announcement-2025-03-19

**Comment by jpa102** [comment]
i just read the newly edited readme.md, good to know

can confirm that spoofing to versions higher than 17.39.35 and below 19.0x.xx causes the app to not load the pages correctly

but oddly enough, spoofing between 19.01.xx and 19.09.xx makes it somewhat bearable (at least for me, this is not the case for everyone using the youtube patches for android 5 though)

but i don't know how reliable it is

**Comment by johncaiwa** [comment]
I get 400 errors on everything, even the library.

Just to confirm, there is no way to use this on Android 6 devices anymore? And there are no plans to update it?

I can't find any settings to spoof the version number.

**Comment by jpa102** [comment]
@johncaiwa at its current state, there will be no future updates for it

as for the spoof app version, press the "Selected patches" and scroll down until you find this:

![Screenshot_20250319_180941_ReVanced Manager A5-7.png](https://github.com/user-attachments/assets/08cc20b5-963f-4545-b03d-d345de18ea0f)

check it to include the patch and you should see the spoof app version option in youtube revanced extended settings

from there, you can try my broken workaround by spoofing it to something like `19.02.39`

**Comment by userunknown358** [comment]
Here's how you can fix this:


1. Disable suggestions
2. Disable EVERYTHING related to shorts
3. Spoof the app to 18.33.01 and restart the app
4. Spoof the app to 19.01

**Comment by userunknown358** [comment]
> Here's how you can fix this:
> 
> 1. Disable suggestions
> 2. Disable EVERYTHING related to shorts
> 3. Spoof the app to 18.33.01 and restart the app
> 4. Spoof the app to 19.01

This option will definitely work but just don't go on shorts as it will cause the app to crash

**Comment by Mtea994** [comment]
@userunknown358 please be kind to specify where are the options needed to be disabled

**Comment by userunknown358** [comment]
> [@userunknown358](https://github.com/userunknown358) please be kind to specify where are the options needed to be disabled

The Hide Siggestions options are in Layout Options

**Comment by Mtea994** [comment]
![Image](https://github.com/user-attachments/assets/c6a3990c-412c-4a3d-8b73-f0fd19ecec2e)
No Layout options here

**Comment by userunknown358** [comment]
> ![Image](https://github.com/user-attachments/assets/c6a3990c-412c-4a3d-8b73-f0fd19ecec2e) No Layout options here

You can search it up

**Comment by jpa102** [comment]
update: i didn't do anything to my builds, but the 17.3x.xx version i was spoofing into suddenly loaded

![Screenshot_20250326_214209.png](https://github.com/user-attachments/assets/07634ee0-0ce7-4db2-a25e-7c7e27ae5fe7)

but there's a nasty surprise behind it (or is it just me?)

![Screenshot_20250326_214225.png](https://github.com/user-attachments/assets/48ee3b15-1c1e-413e-b735-919dd664f33e)

from my other build:

![Screenshot_20250326_215327.png](https://github.com/user-attachments/assets/36563313-9da8-4abf-bbb7-ddc34c5afe4f)

i've read that the 400 error / new update screen was being rolled out to some users in certain countries. and when that happened, i got affected as well (signed in and out)

but now i'm just confused and surprised about this, since this shouldn't be possible

**Comment by xicook** [comment]
It looks like Google has shut down the servers to 17.34.xx and 18.xx.xx, you need to spoof to 19.xx.xx+ to continue using youtube.

**Comment by jpa102** [comment]
i know that, but that will make it crash at startup after a couple of app restarts unless you tinker around in settings

**Comment by userunknown358** [comment]
> i know that, but that will make it crash at startup after a couple of app restarts unless you tinker around in settings

Could opening the app multiple times solve the issue because I tried opeining the app multiple times with YouTube Vanced (15.43.32) and the crash issue was solved but the app configuration will reset (But the error will persist once you re-open the app)

Unsure if this works with 17.33.42

**Comment by jpa102** [comment]
@userunknown358 no, it does not resolve the issue at all. spoofing to versions `19.01.xx` and greater on base clients like `17.34.36`, `16.40.36`, and others will constantly load the "internal layout" that's being sent from youtube servers *(apologize for my wording as i'm just a web dev)*. this kind of layout version has something that makes it crash and one of them is the Library tab turning into You tab

it's literally the same issue, be it with this kind of ReVanced Extended patches for YouTube `17.34.36`, [ReVanced Extended patches for YouTube `16.40.36`](https://github.com/d4n3436/revanced-patches-android5), or [YouTube Vanced apks from codebucket mirror](https://mirror.codebucket.de/)

> Unsure if this works with 17.33.42

the base apk or the spoof version?

**Comment by jpa102** [comment]
@userunknown358 no, it does not resolve the issue at all. spoofing to versions `19.01.xx` and greater on base clients like `17.34.36`, `16.40.36`, and others will constantly load the "internal layout" that's being sent from youtube servers *(apologize for my wording as i'm just a web dev)*. this kind of layout version has something that makes it crash and one of them is the Library tab turning into You tab

i've tested it on one of my builds by the way, and it's even worse on my samsung phone which has its screen badly cracked right now

it's literally the same issue, be it with this kind of ReVanced Extended patches for YouTube `17.34.36`, [ReVanced Extended patches for YouTube `16.40.36`](https://github.com/d4n3436/revanced-patches-android5), or [YouTube Vanced apks from codebucket mirror](https://mirror.codebucket.de/)

> Unsure if this works with 17.33.42

the base apk or the spoof version?

***

apologies for the bump, everyone

**Comment by kitadai31** [comment]
Update released
https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v5.6.2

**Comment by jpa102** [comment]
good to see an update, but unfortunately my main phone has its screen badly cracked so i can't even test this out for myself :(

hoping this kind of method will last for android 6 - 7 users, since i also love old devices (and app versions)
